// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    *JwtToken `json:"login"`
	Register *JwtToken `json:"register"`
}

type BoardOps struct {
	Create *Board `json:"create"`
}

type JwtToken struct {
	Type  string `json:"type"`
	Token string `json:"token"`
}

type ListItemOps struct {
	Create *ListItem `json:"create"`
}

type ListOps struct {
	Create *List `json:"create"`
}

type NewBoard struct {
	Name   string `json:"name"`
	TeamID int    `json:"team_id"`
}

type NewList struct {
	Name    string `json:"name"`
	BoardID int    `json:"board_id"`
}

type NewListItem struct {
	Name   string `json:"name"`
	ListID int    `json:"list_id"`
	Prev   *int   `json:"prev"`
}

type NewTeamHasMember struct {
	TeamID int `json:"team_id"`
	UserID int `json:"user_id"`
}

type NewUser struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type TeamHasMemberOps struct {
	Create *TeamHasMember `json:"create"`
}

type TeamOps struct {
	Create *Team `json:"create"`
}

type UserOps struct {
	EditName   string `json:"edit_name"`
	EditAvatar string `json:"edit_avatar"`
}
