// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthOps struct {
	Login    *JwtToken `json:"login"`
	Register *JwtToken `json:"register"`
}

type Board struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	TeamID    int        `json:"team_id"`
}

type BoardOps struct {
	Create *Board `json:"create"`
}

type JwtToken struct {
	Type  string `json:"type"`
	Token string `json:"token"`
}

type List struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	BoardID   int        `json:"board_id"`
}

type ListOps struct {
	Create string `json:"create"`
}

type NewTeamHasMember struct {
	TeamID int `json:"team_id"`
	UserID int `json:"user_id"`
}

type NewUser struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type Team struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	OwnerID   int        `json:"owner_id"`
}

type TeamHasMember struct {
	ID     int `json:"id"`
	TeamID int `json:"team_id"`
	UserID int `json:"user_id"`
}

type TeamHasMemberOps struct {
	Create *TeamHasMember `json:"create"`
}

type TeamOps struct {
	Create *Team `json:"create"`
}

type User struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	Avatar    *string    `json:"avatar"`
}

type UserOps struct {
	EditName   string `json:"edit_name"`
	EditAvatar string `json:"edit_avatar"`
}
