package config

import (
	"fmt"
	logger "myapp/logger"
	"os"

	mysql "gorm.io/driver/mysql"
	gorm "gorm.io/gorm"
)

//Generated By github.com/david-yappeter/GormCrudGenerator

//ConnectGorm Database Connection to Gorm V2
func ConnectGorm() *gorm.DB {
	databaseConfig := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?multiStatements=true&parseTime=true", os.Getenv("DB_USER"), os.Getenv("DB_PASSWORD"), os.Getenv("DB_HOST"), os.Getenv("DB_PORT"), os.Getenv("DB_DATABASE"))

	db, err := gorm.Open(mysql.Open(databaseConfig), logger.InitConfig())

	if err != nil {
		fmt.Println(err)
		panic("Fail To Connect Database")
	}

	return db
}
