package logger

import (
	"log"
	"os"
	"time"

	gorm "gorm.io/gorm"
	logger "gorm.io/gorm/logger"
	schema "gorm.io/gorm/schema"
)

//Generated By github.com/david-yappeter/GormCrudGenerator

//InitConfig Initialize Config
func InitConfigTest() *gorm.Config {
	return &gorm.Config{
		Logger:         InitLogTest(),
		NamingStrategy: InitNamingStrategyTest(),
	}
}

//InitLog Connection Log Configuration
func InitLogTest() logger.Interface {
	newLogger := logger.New(log.New(os.Stdout, "\r\n", log.LstdFlags), logger.Config{
		Colorful:      true,
		LogLevel:      logger.Info,
		SlowThreshold: time.Second,
	})
	return newLogger
}

//InitNamingStrategy Init NamingStrategy
func InitNamingStrategyTest() *schema.NamingStrategy {
	return &schema.NamingStrategy{
		SingularTable: true,
		TablePrefix:   "",
	}
}
