name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: "Setup MySQL"
        run : |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: "Checkout Code"
        uses: actions/checkout@v2
      
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./tests/
